name: Nodejs CI/CD with Docker

on:
  push:
    branches: [ "main" ]


jobs:

  test-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm test

  build-image:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t oreay/nodejs-cicd:1.0 .
