name: Nodejs CI/CD with Docker

on:
  push:
    branches: [ "main" ]


jobs:

  test-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm test

  build-image:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t oreay/nodejs-cicd:1.0 .
  test-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Run container from image
        run: |
          docker run -d --name temp-container -p 3000:3000 oreay/nodejs-cicd:1.0
      - name: Wait for app to boot
        run: sleep 10
      - name: Health Check
        run: |
          curl --fail http://localhost:3000 || (echo "Health check failed!" && exit 1)
      - name: Stop container
        if: always()
        run: docker rm -f temp-container || true
